### ISSUE TITLE
Is there a plan to add others?

### ISSUE THREAD

**Issue by ToPeas** [phiphou/webpack-vue-demo#1]
1. vuex
2. vue-router
3. vue-touch
3. use repalce  vue-resource to  axios 
4. use repalce webpack-dev-server to  webpack-dev-middleware  for hot-reload
5. use mock.js 

thanks you for answer my question 
my english is poor

**Comment by phiphou** [comment]
Hi,

Yes, I plan to add many features in the coming days/weeks. 

`Vue-router` and `VueX` are on my list, will probably add `vue-touch` too. I also plan to support HotRelod.

I'm currently working on mocking, and have a try with `json-server`, don't know your "mock.js", any link ? 

(I'm french, so don't worry for your english :) )

**Comment by ToPeas** [comment]
thank you .
I'm a Chinese and an entry-level front-end engineer.
mock.js is written by a Chinese similar to json-server ,but i think  json-server is better than mock.js
this is link https://github.com/nuysoft/Mock
I will learn from you to become a good front-end engineers. Thanks again for answering my question. Finally, I have a question, do you think learning Vue, there is a need to learn react (I mean React all)?

**Comment by phiphou** [comment]
You're welcome ); 

> mock.js is written by a Chinese similar to json-server ,but i think json-server is better than mock.js

Don't know if `mock.js` is better or not, but all documentation is in chinese. I don't read it, so will keep `json-server` for now.

> I will learn from you to become a good front-end engineers.

Thank you, but you have to know that I'm using this repo for my `Vue` learning too, don't forget to have a look at others repos, blogs, tutorials...

> Finally, I have a question, do you think learning `Vue`, there is a need to learn react (I mean React all)?

I never used `React` so I'cant give you the most relevant answers, but a good front-end dev cannot be focused on only one framework, and because `React` is one of the most used, I's a good idea to have a look at.
